// SPDX-FileCopyrightText: 2025 blinry <mail@blinry.org>
// SPDX-FileCopyrightText: 2025 zormit <nt4u@kpvn.de>
// SPDX-FileCopyrightText: 2026 axelmartensson <axel.martensson@hotmail.com>
// SPDX-FileCopyrightText: 2026 Caleb Maclennan <caleb@alerque.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Data structures and helper methods around influencing the configuration of the application.

use std::fmt::{Display, Formatter, Result as FmtResult};
use std::ops::Deref;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use docstr::docstr;
use git2::{Config as GitConfig, ConfigLevel};
use ini::{Ini, Properties};
use tempfile::{TempDir, tempdir_in};

use crate::sandbox;
use crate::setup::find_git_repo;
use crate::setup::get_app_cache_dir;
use crate::types::UserInterface;
use crate::wormhole::get_secret_address_from_wormhole;

#[cfg(unix)]
pub(crate) const LISTENER_NAME: &str = "socket";
#[cfg(windows)]
pub(crate) const LISTENER_NAME: &str = "namedpipe";
pub(crate) const CONFIG_DIR: &str = ".teamtype";
pub(crate) const CONFIG_FILE: &str = "config";

const EMIT_JOIN_CODE_DEFAULT: bool = true;
const EMIT_SECRET_ADDRESS_DEFAULT: bool = false;
// TODO: Generate a random funny name.
const USERNAME_FALLBACK: &str = "Anonymous";

/// A peer defines how to look for the other end of a peer-2-peer link.
#[derive(Clone, Debug)]
pub enum Peer {
    /// An Iroh secret address. Holding this likely means we've successfully connected to the Peer
    /// before, but it is possible (if not very safe) to pass around this secret identify as well.
    SecretAddress(String),
    /// If we've yet to connect to a peer, we might only have an magic wormhole invite code
    /// generated by that peer that isn't yet resolved to a secret address.
    JoinCode(String),
}

impl Peer {
    /// Derive a username to identify a client from the join code it used to connect, if any. This
    /// only works once on a client's first connection because after that we join with a verbose
    /// peer id, not a join code. But for first time joiners that don't otherwise have a username
    /// configured it's a nicer fallback than 'Anonymous'.
    pub fn to_username(&self) -> Option<String> {
        let Self::JoinCode(code) = self else {
            return None;
        };
        let username = code
            .split('-')
            .skip(1)
            .take(2)
            .collect::<Vec<_>>()
            .join("-");
        if username.is_empty() {
            None
        } else {
            Some(username)
        }
    }
}

/// Defines the base project directory of a Teamtype share. Everything Teamtype does should be
/// sandboxed in this location and nowhere outside of this location should ever be written to.
#[derive(Debug)]
pub enum ProjectDir {
    /// A directory location that existed prior to starting Teamtype. Whatever files are touched in
    /// the process of a sharing session remain after we shut down.
    Permanent(PathBuf),
    /// A temporary location created by Teamtype for joining remote shares that will that will be
    /// removed as soon as we shut down.
    Temporary(TempDir),
}

impl ProjectDir {
    /// Create a new temporary directory for joining a project for the duration of a share but not
    /// keeping the project locally after disconnecting.
    pub fn new_temporary() -> Result<Self> {
        let parent_dir = get_app_cache_dir()?;
        let tempdir = tempdir_in(&parent_dir).context(format!(
            "Failed to create a temporary directory in the directory {}",
            parent_dir.display()
        ))?;
        Ok(Self::Temporary(tempdir))
    }
}

impl TryFrom<&Path> for ProjectDir {
    type Error = anyhow::Error;

    fn try_from(path: &Path) -> Result<Self> {
        let project_dir = path.canonicalize().with_context(|| {
            format!(
                "Could not compute the absolute, canonical form of the path of directory {}",
                path.display(),
            )
        })?;
        Ok(Self::Permanent(project_dir))
    }
}

impl Deref for ProjectDir {
    type Target = Path;

    fn deref(&self) -> &Self::Target {
        match self {
            Self::Permanent(path) => path,
            Self::Temporary(temp_dir) => temp_dir.path(),
        }
    }
}

impl AsRef<Path> for ProjectDir {
    fn as_ref(&self) -> &Path {
        match self {
            Self::Permanent(path) => path.as_ref(),
            Self::Temporary(dir) => dir.as_ref(),
        }
    }
}

impl Default for ProjectDir {
    /// This will default to the current working directory of the process.
    fn default() -> Self {
        Self::Permanent(PathBuf::default())
    }
}

impl Display for ProjectDir {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self {
            Self::Permanent(path) => write!(f, "{}", path.display()),
            Self::Temporary(temp_dir) => write!(f, "{}", temp_dir.path().display()),
        }
    }
}

impl Clone for ProjectDir {
    fn clone(&self) -> Self {
        match self {
            Self::Permanent(path) => Self::Permanent(path.clone()),
            Self::Temporary(temp_dir) => Self::Permanent(temp_dir.path().to_path_buf()),
        }
    }
}

/// Whether or not to sync version-control directories like `.git/` or `.jj/`.
#[derive(Default, Copy, Clone, Debug, Eq, PartialEq)]
pub enum VcsMode {
    Sync,
    #[default]
    Ignore,
}

#[derive(Default, Copy, Clone, Debug, Eq, PartialEq)]
pub enum NetworkMode {
    #[default]
    Host,
    Peer,
}

#[derive(Default, Debug, Clone)]
pub struct Config {
    /// Base project directory where everything Teamtype does for a share will be sandboxed.
    pub project_dir: ProjectDir,
    /// Remote side of a p2p connection, used by joining peers to find the sharing peer.
    pub peer: Option<Peer>,
    /// Whether or not the sharing peer should output new join codes after each successful joining
    /// peer connection.
    pub emit_join_code: bool,
    /// Whether or not a sharing peer should output its secret ID in the user interface.
    pub emit_secret_address: bool,
    /// Magic Wormhole relay server to use, defaults to a public relay.
    pub magic_wormhole_relay: Option<String>,
    /// Iroh relay server to use, defaults to a public relay.
    pub iroh_relay: Option<String>,
    /// Iroh name resolver to use, defaults to a public resolver.
    pub iroh_dns_domain: Option<String>,
    /// Iroh pkarr relay to use, defaults to a public relay.
    pub iroh_pkarr_relay: Option<String>,
    /// How to handle project directories that are tracked with VCS.
    pub vcs_mode: VcsMode,
    /// Local peer's preferred moniker to be displayed by remote clients.
    pub username: Option<String>,
}

impl Config {
    // Merges the app config from file with the CLI app config by taking the "superset" of them.
    //
    // It depends on the attribute how we're merging it:
    // - For strings, the CLI app config attribute has precedence.
    // - For booleans, if a value deviates from the default, it "wins".
    // - The `project_dir` will be taken from the CLI app config.
    pub fn from_config_file_and_cli(config_cli: Self, ui: &UserInterface) -> Result<Self> {
        let empty_properties_section = Properties::new();
        let project_dir = config_cli.project_dir;
        let conf;
        let config_file = project_dir.join(CONFIG_DIR).join(CONFIG_FILE);
        let general_section = if config_file.exists() {
            conf = Ini::load_from_file(config_file)
                .context("Could not access config file, even though it exists")?;
            conf.general_section()
        } else {
            &empty_properties_section
        };

        // We do the computation of username before initializing the struct, because we need to
        // reference project_dir and peer, which get moved into the struct (and resolved).
        let username = resolve_a_username(
            config_cli.username,
            config_cli.peer.as_ref(),
            general_section,
            &project_dir,
            ui,
        );

        Ok(Self {
            // TODO: extract all the other fields to its own struct, s.t. we don't have to work
            // around the fact that project_dir won't ever be in the config file.
            project_dir,
            peer: config_cli.peer.or_else(|| {
                general_section
                    .get("peer")
                    .map(|p| Peer::SecretAddress(p.to_string()))
            }),
            emit_join_code: config_cli.emit_join_code
                && general_section
                    .get("emit_join_code")
                    .map_or(EMIT_JOIN_CODE_DEFAULT, |ejc| {
                        ejc.parse()
                            .expect("Failed to parse config parameter `emit_join_code` as bool")
                    }),
            emit_secret_address: config_cli.emit_secret_address
                || general_section.get("emit_secret_address").map_or(
                    EMIT_SECRET_ADDRESS_DEFAULT,
                    |esa| {
                        esa.parse().expect(
                            "Failed to parse config parameter `emit_secret_address` as bool",
                        )
                    },
                ),
            magic_wormhole_relay: config_cli.magic_wormhole_relay.or_else(|| {
                general_section
                    .get("magic_wormhole_relay")
                    .map(ToString::to_string)
            }),
            iroh_relay: config_cli
                .iroh_relay
                .or_else(|| general_section.get("iroh_relay").map(ToString::to_string)),
            iroh_dns_domain: config_cli.iroh_dns_domain.or_else(|| {
                general_section
                    .get("iroh_dns_domain")
                    .map(ToString::to_string)
            }),
            iroh_pkarr_relay: config_cli.iroh_pkarr_relay.or_else(|| {
                general_section
                    .get("iroh_pkarr_relay")
                    .map(ToString::to_string)
            }),
            vcs_mode: config_cli.vcs_mode,
            username: Some(username),
        })
    }

    fn config_file(&self) -> PathBuf {
        self.project_dir.join(CONFIG_DIR).join(CONFIG_FILE)
    }

    /// If we have a join code, try to use that and overwrite the config file.
    /// If we don't have a join code, try to use the configured peer.
    /// Otherwise, fail.
    pub async fn resolve_peer(self, ui: &UserInterface) -> Result<Self> {
        let resolved_config = if let Some(peer) = self.peer.clone()
            && let Peer::JoinCode(ref join_code) = peer
        {
            let secret_address =
                get_secret_address_from_wormhole(join_code, self.magic_wormhole_relay.clone(), ui)
                    .await
                    .context(
                        "Failed to retrieve secret address, was this join code already used?",
                    )?;
            ui.log("Derived peer from join code. Storing in config (overwriting previous config).");
            let config_file = self.config_file();
            store_peer_in_config(&self.project_dir, &config_file, &secret_address, ui)?;
            // Create a new Config struct with the resolved peer in place of the join code.
            Self {
                peer: Some(Peer::SecretAddress(secret_address)),
                ..self
            }
        } else {
            // In share mode or with already resolved peers there is no resolution needed.
            self
        };
        Ok(resolved_config)
    }

    pub(crate) const fn network_mode(&self) -> NetworkMode {
        if self.peer.is_none() {
            NetworkMode::Host
        } else {
            NetworkMode::Peer
        }
    }
}

fn store_peer_in_config(
    project_dir: &ProjectDir,
    config_file: &Path,
    peer: &str,
    ui: &UserInterface,
) -> Result<()> {
    ui.log(&format!(
        "Storing peer's address in {}",
        config_file.display()
    ));

    let content = format!("peer={peer}\n");
    sandbox::write_file(project_dir, config_file, content.as_bytes())
        .context("Failed to write to config file")
}

#[must_use]
pub(crate) fn has_git_remote(project_dir: &ProjectDir) -> bool {
    if let Ok(repo) = find_git_repo(project_dir)
        && let Ok(remotes) = repo.remotes()
    {
        return !remotes.is_empty();
    }
    false
}

/// Test if the local Git config has *any* user config.
pub(crate) fn has_local_user_config(project_dir: &ProjectDir) -> Result<bool> {
    let snapshot = find_git_repo(project_dir)?.config()?.snapshot()?;
    let mut entries = snapshot.entries(Some("user\\."))?;
    while let Some(Ok(entry)) = entries.next() {
        match entry.level() {
            ConfigLevel::Local | ConfigLevel::Worktree | ConfigLevel::App => return Ok(true),
            _ => {}
        }
    }
    Ok(false)
}

fn resolve_a_username(
    config_cli_username: Option<String>,
    config_cli_peer: Option<&Peer>,
    general_section: &Properties,
    project_dir: &ProjectDir,
    ui: &UserInterface,
) -> String {
    config_cli_username
        .map(|u| get_username_from_cli(u, ui))
        .or_else(|| get_username_from_config_file(general_section, ui))
        .or_else(|| get_username_from_git(project_dir, ui))
        .or_else(|| get_username_from_join_code(config_cli_peer))
        .unwrap_or_else(|| get_username_from_fallback_value(ui))
}

fn get_username_from_cli(username: String, ui: &UserInterface) -> String {
    ui.log(&format!(
        "Using the CLI provided username '{username}' to display next to the cursors other people see."
    ));
    username
}

fn get_username_from_config_file(
    general_section: &Properties,
    ui: &UserInterface,
) -> Option<String> {
    general_section
        .get("username")
        .map(ToString::to_string)
        .map(|username| {
            ui.log(&format!(
                "Using the username '{username}' from `.teamtype/config` as username, to display next to the cursors other people see."
            ));
            username
        })
}

fn get_username_from_git(project_dir: &ProjectDir, ui: &UserInterface) -> Option<String> {
    let username = get_git_username(project_dir, ui);
    if let Some(ref username) = username {
        ui.log(&docstr!(format!
                /// Using the Git username '{username}' as username, to display next to the cursors other people see.
                /// Teamtype uses the Git username as username by default.
                /// You can set the configuration value `username` in your `.teamtype/config` to override this username.
                /// You can also use the flag `--username` when using the `share`/`join` subcommands.
        ));
    }
    username
}

fn get_username_from_join_code(peer: Option<&Peer>) -> Option<String> {
    peer.and_then(Peer::to_username)
}

fn get_username_from_fallback_value(ui: &UserInterface) -> String {
    let username = USERNAME_FALLBACK.to_string();
    ui.log(&docstr!(format!
        /// Using the fallback value for username '{username}' as username, to display next to the cursors other people see.
        /// You can set the configuration value `username` in your `.teamtype/config` to override this username.
        /// You can also use the flag `--username` when using the `share`/`join` subcommands.
    ));
    username
}

#[must_use]
fn get_git_username(project_dir: &ProjectDir, ui: &UserInterface) -> Option<String> {
    local_git_username(project_dir)
        .or_else(|_| {
            let check_global_anyway: bool = ui
                .confirm(&docstr!(format!
                    /// The directory '{project_dir}' is not initialized as a Git repository.
                    ///
                    /// Should we ascend to the user's home directory to check for a Git username anyway?
                ))
                .unwrap_or(false);
            if check_global_anyway {
                global_git_username()
            } else {
                Err(anyhow!("Not allowed"))
            }
        })
        .ok()
        // If the username is empty, return None. This can happen if Git is installed, but no
        // username is set on any level of Git configuration.
        .filter(|username| !username.is_empty())
}

fn local_git_username(project_dir: &ProjectDir) -> Result<String> {
    Ok(find_git_repo(project_dir)?
        .config()?
        .snapshot()?
        .get_str("user.name")?
        .to_string())
}

fn global_git_username() -> Result<String> {
    Ok(GitConfig::open_default()?
        .snapshot()?
        .get_str("user.name")?
        .to_string())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use anyhow::{Context, Result};
    use tempfile::tempdir;

    use super::ProjectDir;

    #[test]
    fn try_into_projectdir_from_pathbuf() -> Result<()> {
        let temp = tempdir().context("Unable to create directory for tests")?;
        let dir = temp.path();
        let project_dir: ProjectDir = dir.try_into()?;
        match project_dir {
            ProjectDir::Permanent(ref path) => {
                assert_eq!(*path, dir.canonicalize()?);
            }
            ProjectDir::Temporary(_) => panic!("Expected a permanent project directory"),
        }
        drop(project_dir);
        assert!(dir.exists(), "Permanent directory removed by drop");
        Ok(())
    }

    #[test]
    fn try_into_projectdir_from_nonexistent() {
        let nonexistent = PathBuf::from("does-not-exist");
        let result: Result<ProjectDir> = nonexistent.as_path().try_into();
        assert!(result.is_err());
    }

    #[test]
    fn temporary_creates_and_destroys_directory() -> Result<()> {
        let project_dir =
            ProjectDir::new_temporary().context("Unable to create temporary directory")?;
        assert!(
            matches!(project_dir, ProjectDir::Temporary(_)),
            "ProjectDir not an expected temporary directory"
        );
        let path: PathBuf = project_dir.to_path_buf();
        assert!(path.exists(), "Temporary directory was not created");
        drop(project_dir);
        assert!(!path.exists(), "Temporary directory exists after drop");
        Ok(())
    }
}
