# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

edition = "2024"
style_edition = "2024"
unstable_features = true

# We like these options, but don't enforce them in the CI, as they're not stable yet.
# You can install a nightly toolchain and run `cargo +nightly fmt` to apply them to new imports.
group_imports = "StdExternalCrate"
reorder_impl_items = true
