# SPDX-FileCopyrightText: 2026 Caleb Maclennan <caleb@alerque.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# This is the default, but forcing it here makes sure the e2e tests can find it
# relative to the workspace dir env we're also setting even in the event users
# have customized Cargo's default target directory, e.g. to use shared artifacts.
[build]
target-dir = "target"

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
TEAMTYPE_DEBUG_BINARY = { value = "target/debug/teamtype", relative = true }

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]

# Cross-compiling builds dependencies (e.g. Iroh) as DLLs that re-export
# their entire entire API. Attempting to link these into the final build
# ends up exceeding 65,000 symbols — killing GNU's ld argument parsing.
# We don't actually need the symbols to be re-exported in the first place
# since we aren't shipping the intermediary DLLs.
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--exclude-all-symbols"]
