# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: General tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_TEST_DEBUG: 0 # See https://corrode.dev/blog/tips-for-faster-ci-builds/

jobs:
  build_and_test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nvim-version: [v0.12.2]
        include:
          - os: ubuntu-latest
            nvim-version: v0.9.5
          - os: ubuntu-latest
            nvim-version: v0.10.4
          - os: ubuntu-latest
            nvim-version: v0.11.7
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}
      - name: Build Teamtype
        run: cargo build --profile test
      - run: nvim --version
      - name: Compile default tests
        run: cargo test --locked --no-default-features --no-run
      - name: Compile e2e fuzzer
        run: cargo test --locked --no-default-features --no-run --test fuzzer
      - name: Run default unit tests
        run: cargo test --locked --no-default-features -p teamtype
      - name: Run default e2e tests
        run: cargo test --locked --no-default-features -p e2e-tests
      - if: ${{ matrix.nvim-version == 'v0.11.2' }}
        name: Run e2e fuzzer
        run: cargo test --locked --no-default-features -p e2e-tests --test fuzzer

  check_formatting:
    name: Check Rust formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check

  clippy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: --deny warnings
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust toolchain
        run: rustup toolchain install stable --profile minimal --component=clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo clippy --all-targets --all-features
      - run: cargo doc --no-deps --all-features
